[package]
name = "nitro-tpm-attest"
version = "1.0.0"
description = "Retrieve a signed attestation document from the NitroTPM"
edition = "2024"
authors = ["Marius Knaust <mknaust@amazon.com>"]
repository = "https://github.com/aws/NitroTPM-Tools"
readme = "README.md"
license-file = "../LICENSE"
keywords = ["aws", "nitro", "nitrotpm", "attestation", "tpm"]

[dependencies]
anyhow = "1.0"
aws-lc-rs = "1.13"
aws-nitro-enclaves-nsm-api = "0.4"
ciborium = "0.2"
clap = { version = "4.5", features = ["derive"] }
picky-asn1-der = "0.5"
picky-asn1-x509 = "0.12"
serde = "1.0"
serde_bytes = "0.11"
thiserror = "2.0"
tss-esapi = "7.6"
tss-esapi-sys = "0.5"

[build-dependencies]
semver = "1.0"

[dev-dependencies]
aws-config = "1.5"
# AWS SDK version constraints to maintain Rust 1.85 compatibility on AL2023
aws-sdk-kms = "<=1.77"
aws-sdk-sso = "~1.74"
aws-sdk-ssooidc = "~1.75"
aws-sdk-sts = "~1.76"
base64ct = { version = "1.7", features = ["alloc"] }
openssl = "0.10"
tokio = { version = "1", features = ["full"] }

[[example]]
name = "nitro-tpm-kms-decrypt"
path = "examples/kms_decrypt.rs"
