name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: toolchain
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - id: manifest
        run: |
          version="$(cargo metadata --no-deps --format-version 1 \
            | jq --raw-output --exit-status '.metadata."tpm2-tss".version')"

          echo "tpm2-tss-version=$version" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/tpm2-tss
        with:
          version: ${{ steps.manifest.outputs.tpm2-tss-version }}
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-tpm2-tss-${{ steps.manifest.outputs.tpm2-tss-version }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: ./.github/actions/check
  amazon-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ "2023", "2027" ]
    container: amazonlinux:${{ matrix.version }}
    steps:
      - run: >-
          dnf install --assumeyes --setopt=install_weak_deps=False
          git tar gzip gcc pkgconf-pkg-config openssl-devel rust cargo clippy rustfmt tpm2-tss-devel
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: packages
        run: echo "versions=$(rpm --query --queryformat '%{NAME}-%{VERSION}-%{RELEASE}-' rust tpm2-tss-devel)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: amazon-linux-${{ matrix.version }}-${{ steps.packages.outputs.versions }}cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: ./.github/actions/check
  static-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: docker build --file docker/builder.Dockerfile --tag nitro-tpm-tools-builder .
      - run: docker run --rm --tty --volume cargo-cache:/root/.cargo/registry --volume "$PWD:/mnt" nitro-tpm-tools-builder cargo build --bins --examples --locked
      - run: readelf --program-headers ./target/debug/nitro-tpm-attest > headers && ! grep INTERP headers
      - run: readelf --program-headers ./target/debug/nitro-tpm-pcr-compute > headers && ! grep INTERP headers
      - run: readelf --program-headers ./target/debug/examples/nitro-tpm-kms-decrypt > headers && ! grep INTERP headers
